# Generated by Django 4.1.5 on 2023-01-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_profession", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageStat",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="YearStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("salary", models.IntegerField()),
                ("salary_vac", models.IntegerField()),
                ("count", models.IntegerField()),
                ("count_vac", models.IntegerField()),
            ],
        ),
    ]
