# Generated by Django 4.1.5 on 2023-01-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_profession", "0002_imagestat_yearstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=20)),
                ("info", models.CharField(max_length=20)),
            ],
        ),
    ]
