# Generated by Django 4.1.5 on 2023-01-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_profession", "0003_citystat"),
    ]

    operations = [
        migrations.DeleteModel(name="CityStat",),
    ]
